-- Tạo cơ sở dữ liệu và bảng cho hệ thống trung tâm anh ngữ
CREATE DATABASE IF NOT EXISTS app_anh_ngu CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE app_anh_ngu;
SET NAMES utf8mb4;
SET character_set_client = utf8mb4;
SET character_set_connection = utf8mb4;
SET character_set_results = utf8mb4;
SET default_storage_engine = INNODB;
SET foreign_key_checks = 0;

CREATE TABLE IF NOT EXISTS QuanTriVien (
    MaQuanTriVien INT AUTO_INCREMENT PRIMARY KEY,
    TenDangNhap VARCHAR(100) NOT NULL UNIQUE,
    MatKhau VARCHAR(255) NOT NULL,
    HoTen VARCHAR(255) NOT NULL,
    Email VARCHAR(255) DEFAULT NULL,
    PhanQuyen VARCHAR(50) DEFAULT 'admin',
    TrangThai TINYINT(1) DEFAULT 1,
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS HocVien (
    MaHocVien INT AUTO_INCREMENT PRIMARY KEY,
    TenDangNhap VARCHAR(100) NOT NULL UNIQUE,
    MatKhau VARCHAR(255) NOT NULL,
    HoTen VARCHAR(255) NOT NULL,
    Email VARCHAR(255) DEFAULT NULL,
    NgaySinh DATE DEFAULT NULL,
    GioiTinh TINYINT(1) DEFAULT 0,
    TrangThai TINYINT(1) DEFAULT 1,
    SoDienThoai VARCHAR(50) DEFAULT NULL,
    DiaChi VARCHAR(255) DEFAULT NULL,
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS GiaoVien (
    MaGiaoVien INT AUTO_INCREMENT PRIMARY KEY,
    TenDangNhap VARCHAR(100) NOT NULL UNIQUE,
    MatKhau VARCHAR(255) NOT NULL,
    HoTen VARCHAR(255) NOT NULL,
    Email VARCHAR(255) DEFAULT NULL,
    NgaySinh DATE DEFAULT NULL,
    GioiTinh TINYINT(1) DEFAULT 0,
    TrangThai TINYINT(1) DEFAULT 1,
    SoDienThoai VARCHAR(50) DEFAULT NULL,
    DiaChi VARCHAR(255) DEFAULT NULL,
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS KhoaHoc (
    MaKhoaHoc INT AUTO_INCREMENT PRIMARY KEY,
    TenKhoaHoc VARCHAR(255) NOT NULL,
    TrinhDo VARCHAR(100) DEFAULT NULL,
    MoTa TEXT DEFAULT NULL,
    NgayBatDau DATE DEFAULT NULL,
    NgayKetThuc DATE DEFAULT NULL,
    TrangThai VARCHAR(50) DEFAULT 'active',
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS LopHoc (
    MaLop INT AUTO_INCREMENT PRIMARY KEY,
    TenLop VARCHAR(255) NOT NULL,
    MaKhoaHoc INT NOT NULL,
    MaGiaoVien INT DEFAULT NULL,
    SoLuongToiDa INT DEFAULT 0,
    TrangThai VARCHAR(50) DEFAULT 'active',
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaKhoaHoc) REFERENCES KhoaHoc(MaKhoaHoc) ON DELETE CASCADE,
    FOREIGN KEY (MaGiaoVien) REFERENCES GiaoVien(MaGiaoVien) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS BaiHoc (
    MaBaiHoc INT AUTO_INCREMENT PRIMARY KEY,
    TieuDe VARCHAR(255) NOT NULL,
    NoiDung TEXT DEFAULT NULL,
    ThuTu INT DEFAULT 1,
    MaKhoaHoc INT NOT NULL,
    TrangThai VARCHAR(50) DEFAULT 'active',
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaKhoaHoc) REFERENCES KhoaHoc(MaKhoaHoc) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CauHoi (
    MaCauHoi INT AUTO_INCREMENT PRIMARY KEY,
    MaBaiHoc INT DEFAULT NULL,
    NoiDung TEXT NOT NULL,
    LoaiCauHoi VARCHAR(100) DEFAULT NULL,
    ThuTu INT DEFAULT 0,
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaBaiHoc) REFERENCES BaiHoc(MaBaiHoc) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS DapAn (
    MaDapAn INT AUTO_INCREMENT PRIMARY KEY,
    MaCauHoi INT NOT NULL,
    NoiDung TEXT DEFAULT NULL,
    LaDapAnDung TINYINT(1) DEFAULT 0,
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaCauHoi) REFERENCES CauHoi(MaCauHoi) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BaiKiemTra (
    MaBaiKiemTra INT AUTO_INCREMENT PRIMARY KEY,
    MaLop INT DEFAULT NULL,
    TenBaiKiemTra VARCHAR(255) NOT NULL,
    ThoiGianLam INT DEFAULT 60,
    DiemDat DECIMAL(5,2) DEFAULT 0,
    TrangThai VARCHAR(50) DEFAULT 'active',
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaLop) REFERENCES LopHoc(MaLop) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS DangKyLop (
    MaDangKy INT AUTO_INCREMENT PRIMARY KEY,
    MaHocVien INT NOT NULL,
    MaLop INT NOT NULL,
    NgayDangKy DATE DEFAULT NULL,
    TrangThai VARCHAR(50) DEFAULT 'pending',
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaHocVien) REFERENCES HocVien(MaHocVien) ON DELETE CASCADE,
    FOREIGN KEY (MaLop) REFERENCES LopHoc(MaLop) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ChuyenCan (
    MaChuyenCan INT AUTO_INCREMENT PRIMARY KEY,
    MaHocVien INT NOT NULL,
    MaLop INT NOT NULL,
    NgayDiem DATE DEFAULT NULL,
    TrangThai VARCHAR(50) DEFAULT 'Có',
    GhiChu TEXT DEFAULT NULL,
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaHocVien) REFERENCES HocVien(MaHocVien) ON DELETE CASCADE,
    FOREIGN KEY (MaLop) REFERENCES LopHoc(MaLop) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TienDoHocTap (
    MaTienDo INT AUTO_INCREMENT PRIMARY KEY,
    MaHocVien INT NOT NULL,
    MaBaiHoc INT NOT NULL,
    PhanTramHoanThanh DECIMAL(5,2) DEFAULT 0,
    NgayCapNhat DATE DEFAULT NULL,
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaHocVien) REFERENCES HocVien(MaHocVien) ON DELETE CASCADE,
    FOREIGN KEY (MaBaiHoc) REFERENCES BaiHoc(MaBaiHoc) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DanhGiaHocVien (
    MaDanhGia INT AUTO_INCREMENT PRIMARY KEY,
    MaHocVien INT NOT NULL,
    MaGiaoVien INT DEFAULT NULL,
    DiemDanhGia DECIMAL(5,2) DEFAULT 0,
    NhanXet TEXT DEFAULT NULL,
    NgayDanhGia DATE DEFAULT NULL,
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaHocVien) REFERENCES HocVien(MaHocVien) ON DELETE CASCADE,
    FOREIGN KEY (MaGiaoVien) REFERENCES GiaoVien(MaGiaoVien) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS KetQuaLamBai (
    MaKetQua INT AUTO_INCREMENT PRIMARY KEY,
    MaHocVien INT NOT NULL,
    MaBaiHoc INT NOT NULL,
    Diem DECIMAL(5,2) DEFAULT 0,
    SoCauDung INT DEFAULT 0,
    TongSoCau INT DEFAULT 0,
    NgayLam DATE DEFAULT NULL,
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaHocVien) REFERENCES HocVien(MaHocVien) ON DELETE CASCADE,
    FOREIGN KEY (MaBaiHoc) REFERENCES BaiHoc(MaBaiHoc) ON DELETE CASCADE
);

SET foreign_key_checks = 1;
