-- AlterTable
ALTER TABLE `danhmuc` ADD COLUMN `CreatedAt` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    ADD COLUMN `IsDeleted` BOOLEAN NULL DEFAULT false,
    ADD COLUMN `UpdatedAt` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0);
