-- AlterTable
ALTER TABLE `cahoc` ADD COLUMN `CreatedAt` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    ADD COLUMN `UpdatedAt` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `phonghoc` ADD COLUMN `CreatedAt` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    ADD COLUMN `UpdatedAt` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0);
